DROP DATABASE IF EXISTS `security`;
CREATE DATABASE `security`;
USE `security`;

CREATE TABLE APP_USER (
    USER_ID BIGINT NOT NULL,
    USER_NAME VARCHAR(36) NOT NULL,
    ENCRYTED_PASSWORD VARCHAR(128) NOT NULL,
    ENABLED BIT NOT NULL
);
ALTER TABLE APP_USER ADD CONSTRAINT APP_USER_PK PRIMARY KEY (USER_ID);

ALTER TABLE APP_USER ADD CONSTRAINT APP_USER_UK UNIQUE (USER_NAME);

CREATE TABLE APP_ROLE (
    ROLE_ID BIGINT NOT NULL,
    ROLE_NAME VARCHAR(30) NOT NULL
);
ALTER TABLE APP_ROLE ADD CONSTRAINT APP_ROLE_PK PRIMARY KEY (ROLE_ID);

ALTER TABLE APP_ROLE ADD CONSTRAINT APP_ROLE_UK UNIQUE (ROLE_NAME);


CREATE TABLE USER_ROLE (
    ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL
);
ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_PK PRIMARY KEY (ID);

ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_UK UNIQUE (USER_ID, ROLE_ID);

ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_FK1 FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID);

ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_FK2 FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLE (ROLE_ID);

CREATE TABLE Persistent_Logins (
    username VARCHAR(64) NOT NULL,
    series VARCHAR(64) NOT NULL,
    token VARCHAR(64) NOT NULL,
    last_used TIMESTAMP NOT NULL,
    PRIMARY KEY (series)
);

INSERT INTO App_User (USER_ID, USER_NAME, ENCRYTED_PASSWORD, ENABLED) VALUES (2, 'dbuser1', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1);

INSERT INTO App_User (USER_ID, USER_NAME, ENCRYTED_PASSWORD, ENABLED) VALUES (1, 'dbadmin1', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1);

INSERT INTO app_role (ROLE_ID, ROLE_NAME) VALUES (1, 'ROLE_ADMIN');

INSERT INTO app_role (ROLE_ID, ROLE_NAME) VALUES (2, 'ROLE_USER');

INSERT INTO user_role (ID, USER_ID, ROLE_ID) VALUES (1, 1, 1);

INSERT INTO user_role (ID, USER_ID, ROLE_ID) VALUES (2, 1, 2);

INSERT INTO user_role (ID, USER_ID, ROLE_ID) VALUES (3, 2, 2);
